// Emoji data mapping - lightweight and decoupled
export interface EmojiData {
  name: string;
  char: string;
  keywords: string[];
}

export const EMOJI_MAP: Record<string, EmojiData> = {
  // Faces & Emotions
  'smile': { name: 'smile', char: '😊', keywords: ['happy', 'joy', 'pleased'] },
  'grinning': { name: 'grinning', char: '😀', keywords: ['happy', 'smiley', 'emotion'] },
  'grin': { name: 'grin', char: '😁', keywords: ['happy', 'smile', 'joy'] },
  'joy': { name: 'joy', char: '😂', keywords: ['happy', 'tears', 'lol'] },
  'smiley': { name: 'smiley', char: '😃', keywords: ['happy', 'joy', 'haha'] },
  'smile_with_eyes': { name: 'smile_with_eyes', char: '😄', keywords: ['happy', 'joy', 'funny'] },
  'sweat_smile': { name: 'sweat_smile', char: '😅', keywords: ['hot', 'happy', 'laugh', 'sweat'] },
  'rofl': { name: 'rofl', char: '🤣', keywords: ['lol', 'laughing', 'funny'] },
  'relaxed': { name: 'relaxed', char: '☺️', keywords: ['blush', 'massage', 'happiness'] },
  'blush': { name: 'blush', char: '😊', keywords: ['crush', 'embarrassed', 'happy'] },
  'innocent': { name: 'innocent', char: '😇', keywords: ['angel', 'halo'] },
  'slightly_smiling': { name: 'slightly_smiling', char: '🙂', keywords: ['happy', 'positive'] },
  'upside_down': { name: 'upside_down', char: '🙃', keywords: ['flipped', 'silly'] },
  'heart_eyes': { name: 'heart_eyes', char: '😍', keywords: ['love', 'like', 'affection', 'valentines', 'infatuation', 'crush'] },
  'star_struck': { name: 'star_struck', char: '🤩', keywords: ['eyes', 'star', 'amazed'] },
  'kissing_heart': { name: 'kissing_heart', char: '😘', keywords: ['love', 'like', 'affection', 'valentines'] },
  'kissing': { name: 'kissing', char: '😗', keywords: ['love', 'like', 'affection', 'valentines'] },
  'kissing_smiling_eyes': { name: 'kissing_smiling_eyes', char: '😙', keywords: ['love', 'like', 'affection', 'valentines'] },
  'kissing_closed_eyes': { name: 'kissing_closed_eyes', char: '😚', keywords: ['love', 'like', 'affection', 'valentines'] },
  'yum': { name: 'yum', char: '😋', keywords: ['tongue', 'lick', 'nervous', 'tasty', 'playful'] },
  'stuck_out_tongue': { name: 'stuck_out_tongue', char: '😛', keywords: ['prank', 'childish', 'playful', 'mocking', 'tongue'] },
  'stuck_out_tongue_winking_eye': { name: 'stuck_out_tongue_winking_eye', char: '😜', keywords: ['prank', 'childish', 'playful', 'mocking', 'tongue'] },
  'zany_face': { name: 'zany_face', char: '🤪', keywords: ['goofy', 'wacky', 'crazy'] },
  'stuck_out_tongue_closed_eyes': { name: 'stuck_out_tongue_closed_eyes', char: '😝', keywords: ['prank', 'playful', 'mocking', 'tongue'] },
  'money_mouth': { name: 'money_mouth', char: '🤑', keywords: ['rich', 'money', 'cash'] },
  'hugs': { name: 'hugs', char: '🤗', keywords: ['hug', 'thank you'] },
  'hand_over_mouth': { name: 'hand_over_mouth', char: '🤭', keywords: ['quiet', 'whoops', 'shock', 'surprise'] },
  'shushing_face': { name: 'shushing_face', char: '🤫', keywords: ['quiet', 'shhh', 'whisper', 'hush'] },
  'nerd': { name: 'nerd', char: '🤓', keywords: ['nerdy', 'geek', 'dork'] },
  'sunglasses': { name: 'sunglasses', char: '😎', keywords: ['cool', 'summer', 'beach', 'sunglass'] },
  'heart': { name: 'heart', char: '❤️', keywords: ['love', 'like', 'valentine'] },
  'fire': { name: 'fire', char: '🔥', keywords: ['hot', 'burn', 'flame'] },
  'thumbs_up': { name: 'thumbs_up', char: '👍', keywords: ['good', 'approve', 'like'] },
  'thumbs_down': { name: 'thumbs_down', char: '👎', keywords: ['bad', 'disapprove', 'dislike'] },
  'laugh': { name: 'laugh', char: '😂', keywords: ['funny', 'lol', 'haha'] },
  'cry': { name: 'cry', char: '😢', keywords: ['sad', 'tear', 'upset'] },
  'wink': { name: 'wink', char: '😉', keywords: ['flirt', 'joke', 'playful'] },
  'cool': { name: 'cool', char: '😎', keywords: ['sunglasses', 'awesome', 'swag'] },
  'thinking': { name: 'thinking', char: '🤔', keywords: ['hmm', 'wonder', 'ponder'] },
  'smirk': { name: 'smirk', char: '😏', keywords: ['smug', 'sly', 'suggestive'] },
  'neutral_face': { name: 'neutral_face', char: '😐', keywords: ['indifference', 'meh', 'deadpan'] },
  'expressionless': { name: 'expressionless', char: '😑', keywords: ['indifferent', 'meh', 'blank'] },
  'no_mouth': { name: 'no_mouth', char: '😶', keywords: ['mute', 'silence', 'quiet'] },
  'roll_eyes': { name: 'roll_eyes', char: '🙄', keywords: ['sarcastic', 'whatever'] },
  'grimacing': { name: 'grimacing', char: '😬', keywords: ['grimace', 'awkward'] },
  'lying_face': { name: 'lying_face', char: '🤥', keywords: ['liar', 'pinocchio'] },
  'relieved': { name: 'relieved', char: '😌', keywords: ['relaxed', 'phew'] },
  'pensive': { name: 'pensive', char: '😔', keywords: ['sad', 'depressed', 'upset'] },
  'sleepy': { name: 'sleepy', char: '😪', keywords: ['tired', 'rest'] },
  'drooling_face': { name: 'drooling_face', char: '🤤', keywords: ['drool', 'hungry'] },
  'sleeping': { name: 'sleeping', char: '😴', keywords: ['tired', 'sleepy', 'night', 'zzz'] },
  'mask': { name: 'mask', char: '😷', keywords: ['sick', 'ill', 'disease'] },
  'face_with_thermometer': { name: 'face_with_thermometer', char: '🤒', keywords: ['sick', 'temperature', 'thermometer', 'fever', 'ill'] },
  'face_with_head_bandage': { name: 'face_with_head_bandage', char: '🤕', keywords: ['injured', 'clumsy', 'bandage', 'hurt'] },
  'nauseated_face': { name: 'nauseated_face', char: '🤢', keywords: ['vomit', 'gross', 'green', 'sick'] },
  'vomiting_face': { name: 'vomiting_face', char: '🤮', keywords: ['spew', 'sick'] },
  'sneezing_face': { name: 'sneezing_face', char: '🤧', keywords: ['achoo', 'sick'] },
  'hot_face': { name: 'hot_face', char: '🥵', keywords: ['heat', 'sweating'] },
  'cold_face': { name: 'cold_face', char: '🥶', keywords: ['freezing', 'ice'] },
  'woozy_face': { name: 'woozy_face', char: '🥴', keywords: ['dizzy', 'intoxicated'] },
  'dizzy_face': { name: 'dizzy_face', char: '😵', keywords: ['spent', 'unconscious'] },
  'exploding_head': { name: 'exploding_head', char: '🤯', keywords: ['mind', 'blown'] },
  'cowboy': { name: 'cowboy', char: '🤠', keywords: ['hat', 'western'] },
  'partying_face': { name: 'partying_face', char: '🥳', keywords: ['celebration', 'birthday', 'party'] },
  'disguised_face': { name: 'disguised_face', char: '🥸', keywords: ['pretent', 'brows', 'glasses', 'moustache'] },
  'confused': { name: 'confused', char: '😕', keywords: ['indifference', 'huh', 'weird', 'hmmm'] },
  'worried': { name: 'worried', char: '😟', keywords: ['concern', 'nervous'] },
  'slightly_frowning': { name: 'slightly_frowning', char: '🙁', keywords: ['disappointed', 'sad'] },
  'frowning': { name: 'frowning', char: '☹️', keywords: ['upset', 'sad'] },
  'open_mouth': { name: 'open_mouth', char: '😮', keywords: ['surprise', 'impressed', 'wow'] },
  'hushed': { name: 'hushed', char: '😯', keywords: ['woo', 'shh'] },
  'astonished': { name: 'astonished', char: '😲', keywords: ['xox', 'surprised', 'gasps'] },
  'flushed': { name: 'flushed', char: '😳', keywords: ['shy', 'blush', 'flattered'] },
  'pleading_face': { name: 'pleading_face', char: '🥺', keywords: ['puppy', 'dog', 'eyes', 'sad', 'cute', 'beg'] },
  'frowning2': { name: 'frowning2', char: '😦', keywords: ['upset', 'frown', 'sad'] },
  'anguished': { name: 'anguished', char: '😧', keywords: ['stunned', 'nervous'] },
  'fearful': { name: 'fearful', char: '😨', keywords: ['scared', 'terrified', 'nervous'] },
  'cold_sweat': { name: 'cold_sweat', char: '😰', keywords: ['nervous', 'sweat'] },
  'disappointed_relieved': { name: 'disappointed_relieved', char: '😥', keywords: ['phew', 'sweat', 'nervous'] },
  'sob': { name: 'sob', char: '😭', keywords: ['sad', 'cry', 'bawling'] },
  'scream': { name: 'scream', char: '😱', keywords: ['horror', 'shocked'] },
  'confounded': { name: 'confounded', char: '😖', keywords: ['confused', 'sick', 'unwell', 'oops', 'doh'] },
  'persevere': { name: 'persevere', char: '😣', keywords: ['struggling', 'struggling'] },
  'disappointed': { name: 'disappointed', char: '😞', keywords: ['sad', 'upset', 'depressed'] },
  'sweat': { name: 'sweat', char: '😓', keywords: ['worried', 'hot'] },
  'weary': { name: 'weary', char: '😩', keywords: ['tired', 'sleepy', 'sad', 'frustrated', 'upset'] },
  'tired_face': { name: 'tired_face', char: '😫', keywords: ['sick', 'whine', 'upset', 'frustrated'] },
  'yawning_face': { name: 'yawning_face', char: '🥱', keywords: ['tired', 'sleepy'] },
  'triumph': { name: 'triumph', char: '😤', keywords: ['gas', 'phew', 'proud', 'pride'] },
  'rage': { name: 'rage', char: '😡', keywords: ['angry', 'mad', 'hate', 'despise'] },
  'angry': { name: 'angry', char: '😠', keywords: ['mad', 'annoyed', 'frustrated'] },
  'cursing_face': { name: 'cursing_face', char: '🤬', keywords: ['foul', 'cursing', 'profanity', 'expletive'] },
  'smiling_imp': { name: 'smiling_imp', char: '😈', keywords: ['devil', 'horns'] },
  'imp': { name: 'imp', char: '👿', keywords: ['devil', 'angry', 'horns'] },
  
  // Gestures & People
  'clap': { name: 'clap', char: '👏', keywords: ['applause', 'good job', 'bravo'] },
  'wave': { name: 'wave', char: '👋', keywords: ['hello', 'goodbye', 'hi'] },
  'ok_hand': { name: 'ok_hand', char: '👌', keywords: ['fingers', 'limbs', 'perfect', 'ok'] },
  'pinched_fingers': { name: 'pinched_fingers', char: '🤌', keywords: ['size', 'tiny', 'small'] },
  'pinching_hand': { name: 'pinching_hand', char: '🤏', keywords: ['tiny', 'small', 'size'] },
  'v': { name: 'v', char: '✌️', keywords: ['fingers', 'ohyeah', 'hand', 'peace', 'victory', 'two'] },
  'crossed_fingers': { name: 'crossed_fingers', char: '🤞', keywords: ['good', 'lucky'] },
  'love_you_gesture': { name: 'love_you_gesture', char: '🤟', keywords: ['love-you', 'ily'] },
  'metal': { name: 'metal', char: '🤘', keywords: ['devil', 'fingers', 'evil eye', 'sign of horns', 'rock on'] },
  'call_me': { name: 'call_me', char: '🤙', keywords: ['hands', 'gesture'] },
  'point_left': { name: 'point_left', char: '👈', keywords: ['direction', 'indicate'] },
  'point_right': { name: 'point_right', char: '👉', keywords: ['direction', 'indicate'] },
  'point_up_2': { name: 'point_up_2', char: '👆', keywords: ['fingers', 'hand', 'direction', 'up'] },
  'middle_finger': { name: 'middle_finger', char: '🖕', keywords: ['finger', 'rude', 'middle', 'flipping'] },
  'point_down': { name: 'point_down', char: '👇', keywords: ['direction', 'down', 'below'] },
  'point_up': { name: 'point_up', char: '☝️', keywords: ['hand', 'fingers', 'direction', 'up'] },
  'raised_hand': { name: 'raised_hand', char: '✋', keywords: ['fingers', 'stop', 'highfive', 'palm', 'ban'] },
  'raised_back_of_hand': { name: 'raised_back_of_hand', char: '🤚', keywords: ['fingers', 'raised', 'backhand'] },
  'hand_splayed': { name: 'hand_splayed', char: '🖐️', keywords: ['fingers', 'palm'] },
  'vulcan': { name: 'vulcan', char: '🖖', keywords: ['fingers', 'hand', 'spock', 'star trek'] },
  'handshake': { name: 'handshake', char: '🤝', keywords: ['agreement', 'shake'] },
  'pray': { name: 'pray', char: '🙏', keywords: ['please', 'hope', 'wish', 'namaste', 'highfive'] },
  'writing_hand': { name: 'writing_hand', char: '✍️', keywords: ['lower_left_ballpoint_pen', 'stationery', 'write', 'compose'] },
  'nail_care': { name: 'nail_care', char: '💅', keywords: ['beauty', 'manicure', 'finger', 'fashion', 'nail'] },
  'selfie': { name: 'selfie', char: '🤳', keywords: ['camera', 'phone'] },
  'muscle': { name: 'muscle', char: '💪', keywords: ['arm', 'flex', 'hand', 'summer', 'strong'] },
  'mechanical_arm': { name: 'mechanical_arm', char: '🦾', keywords: ['accessibility'] },
  'mechanical_leg': { name: 'mechanical_leg', char: '🦿', keywords: ['accessibility'] },
  'leg': { name: 'leg', char: '🦵', keywords: ['kick', 'limb'] },
  'foot': { name: 'foot', char: '🦶', keywords: ['kick', 'stomp'] },
  'ear': { name: 'ear', char: '👂', keywords: ['face', 'hear', 'sound', 'listen'] },
  'ear_with_hearing_aid': { name: 'ear_with_hearing_aid', char: '🦻', keywords: ['accessibility'] },
  'nose': { name: 'nose', char: '👃', keywords: ['smell', 'sniff'] },
  'brain': { name: 'brain', char: '🧠', keywords: ['smart', 'intelligent'] },
  'anatomical_heart': { name: 'anatomical_heart', char: '🫀', keywords: ['health', 'heartbeat'] },
  'lungs': { name: 'lungs', char: '🫁', keywords: ['breathe'] },
  'tooth': { name: 'tooth', char: '🦷', keywords: ['teeth', 'dentist'] },
  'bone': { name: 'bone', char: '🦴', keywords: ['skeleton'] },
  'eyes': { name: 'eyes', char: '👀', keywords: ['look', 'watch', 'stalk', 'peek', 'see'] },
  'eye': { name: 'eye', char: '👁️', keywords: ['face', 'look', 'see', 'watch', 'stare', 'peek', 'voyeur'] },
  'tongue': { name: 'tongue', char: '👅', keywords: ['mouth', 'playful'] },
  'lips': { name: 'lips', char: '👄', keywords: ['mouth', 'kiss'] },
  
  // Objects & Symbols  
  'rocket': { name: 'rocket', char: '🚀', keywords: ['space', 'launch', 'fast'] },
  'star': { name: 'star', char: '⭐', keywords: ['favorite', 'rating', 'quality'] },
  'glowing_star': { name: 'glowing_star', char: '🌟', keywords: ['glow'] },
  'dizzy': { name: 'dizzy', char: '💫', keywords: ['star', 'sparkle', 'shoot', 'magic'] },
  'sparkles': { name: 'sparkles', char: '✨', keywords: ['stars', 'shine', 'shiny', 'cool', 'awesome', 'good', 'magic'] },
  'zap': { name: 'zap', char: '⚡', keywords: ['thunder', 'weather', 'lightning bolt', 'fast'] },
  'boom': { name: 'boom', char: '💥', keywords: ['bomb', 'explode', 'explosion', 'collision', 'blown'] },
  'fire_engine': { name: 'fire_engine', char: '🚒', keywords: ['vehicle', 'cars'] },
  'droplet': { name: 'droplet', char: '💧', keywords: ['water', 'drip', 'faucet', 'spring'] },
  'ocean': { name: 'ocean', char: '🌊', keywords: ['sea', 'water', 'wave', 'nature', 'tsunami', 'disaster'] },
  'christmas_tree': { name: 'christmas_tree', char: '🎄', keywords: ['festival', 'vacation', 'december', 'xmas', 'celebration'] },
  'sparkler': { name: 'sparkler', char: '🎇', keywords: ['stars', 'night', 'shine'] },
  'fireworks': { name: 'fireworks', char: '🎆', keywords: ['festival', 'party', 'explosion', 'happiness', 'celebrate'] },
  'sun': { name: 'sun', char: '☀️', keywords: ['weather', 'nature', 'brightness', 'summer', 'beach', 'spring'] },
  'sunny': { name: 'sunny', char: '🌞', keywords: ['kearney', 'sky', 'morning', 'summer'] },
  'partly_sunny': { name: 'partly_sunny', char: '⛅', keywords: ['weather', 'nature', 'cloudy', 'morning', 'fall', 'spring'] },
  'cloud': { name: 'cloud', char: '☁️', keywords: ['weather', 'sky'] },
  'lightning': { name: 'lightning', char: '⚡', keywords: ['fast', 'energy', 'power'] },
  'check': { name: 'check', char: '✅', keywords: ['done', 'complete', 'correct'] },
  'x': { name: 'x', char: '❌', keywords: ['wrong', 'error', 'no'] },
  'o': { name: 'o', char: '⭕', keywords: ['circle', 'round'] },
  'warning': { name: 'warning', char: '⚠️', keywords: ['caution', 'alert', 'attention'] },
  'info': { name: 'info', char: 'ℹ️', keywords: ['information', 'help', 'details'] },
  'question': { name: 'question', char: '❓', keywords: ['help', 'unknown', 'confused'] },
  'grey_question': { name: 'grey_question', char: '❔', keywords: ['doubts', 'gray', 'huh', 'confused'] },
  'exclamation': { name: 'exclamation', char: '❗', keywords: ['important', 'alert', 'attention'] },
  'grey_exclamation': { name: 'grey_exclamation', char: '❕', keywords: ['surprise', 'punctuation', 'gray', 'wow', 'warning'] },
  'trident': { name: 'trident', char: '🔱', keywords: ['weapon', 'spear', 'three'] },
  'fleur_de_lis': { name: 'fleur_de_lis', char: '⚜️', keywords: ['decorative', 'scout'] },
  'part_alternation_mark': { name: 'part_alternation_mark', char: '〽️', keywords: ['graph', 'presentation', 'stats', 'business', 'economics', 'bad'] },
  'bangbang': { name: 'bangbang', char: '‼️', keywords: ['exclamation', 'surprise'] },
  'interrobang': { name: 'interrobang', char: '⁉️', keywords: ['wat', 'punctuation', 'surprise'] },
  '100': { name: '100', char: '💯', keywords: ['score', 'perfect', 'numbers', 'century', 'exam', 'quiz', 'test', 'pass', 'hundred'] },
  'diamond_shape_with_a_dot_inside': { name: 'diamond_shape_with_a_dot_inside', char: '💠', keywords: ['jewel', 'blue', 'gem', 'crystal', 'fancy'] },
  
  // Activities & Food
  'party': { name: 'party', char: '🎉', keywords: ['celebration', 'confetti', 'happy'] },
  'gift': { name: 'gift', char: '🎁', keywords: ['present', 'surprise', 'birthday'] },
  'cake': { name: 'cake', char: '🎂', keywords: ['birthday', 'dessert', 'celebration'] },
  'balloon': { name: 'balloon', char: '🎈', keywords: ['party', 'celebration', 'birthday', 'circus'] },
  'tada': { name: 'tada', char: '🎊', keywords: ['party', 'congratulations', 'birthday', 'magic', 'circus', 'celebration'] },
  'confetti_ball': { name: 'confetti_ball', char: '🎊', keywords: ['festival', 'party', 'birthday', 'circus'] },
  'coffee': { name: 'coffee', char: '☕', keywords: ['drink', 'morning', 'caffeine'] },
  'tea': { name: 'tea', char: '🍵', keywords: ['drink', 'bowl', 'breakfast', 'green', 'british'] },
  'sake': { name: 'sake', char: '🍶', keywords: ['wine', 'drink', 'drunk', 'beverage', 'japanese', 'alcohol', 'booze'] },
  'champagne': { name: 'champagne', char: '🍾', keywords: ['drink', 'wine', 'bottle', 'celebration'] },
  'wine_glass': { name: 'wine_glass', char: '🍷', keywords: ['drink', 'beverage', 'drunk', 'alcohol', 'booze'] },
  'cocktail': { name: 'cocktail', char: '🍸', keywords: ['drink', 'drunk', 'alcohol', 'beverage', 'booze', 'mojito'] },
  'tropical_drink': { name: 'tropical_drink', char: '🍹', keywords: ['beverage', 'cocktail', 'summer', 'beach', 'alcohol', 'booze', 'mojito'] },
  'beer': { name: 'beer', char: '🍺', keywords: ['relax', 'beverage', 'drink', 'drunk', 'party', 'pub', 'summer', 'alcohol', 'booze'] },
  'beers': { name: 'beers', char: '🍻', keywords: ['relax', 'beverage', 'drink', 'drunk', 'party', 'pub', 'summer', 'alcohol', 'booze'] },
  'clinking_glasses': { name: 'clinking_glasses', char: '🥂', keywords: ['beverage', 'drink', 'party', 'alcohol', 'celebrate', 'cheers', 'wine', 'champagne', 'toast'] },
  'tumbler_glass': { name: 'tumbler_glass', char: '🥃', keywords: ['drink', 'beverage', 'drunk', 'alcohol', 'liquor', 'booze', 'bourbon', 'scotch', 'whisky', 'glass', 'shot'] },
  'pizza': { name: 'pizza', char: '🍕', keywords: ['food', 'italian', 'slice'] },
  'hamburger': { name: 'hamburger', char: '🍔', keywords: ['meat', 'fast food', 'beef', 'cheeseburger', 'mcdonalds', 'burger king'] },
  'fries': { name: 'fries', char: '🍟', keywords: ['food', 'fastfood', 'potato', 'french'] },
  'hotdog': { name: 'hotdog', char: '🌭', keywords: ['food', 'frankfurter', 'america'] },
  'sandwich': { name: 'sandwich', char: '🥪', keywords: ['food', 'lunch', 'bread', 'toast', 'bakery'] },
  'taco': { name: 'taco', char: '🌮', keywords: ['food', 'mexican'] },
  'burrito': { name: 'burrito', char: '🌯', keywords: ['food', 'mexican'] },
  'stuffed_flatbread': { name: 'stuffed_flatbread', char: '🥙', keywords: ['food', 'gyro', 'mediterranean'] },
  'bacon': { name: 'bacon', char: '🥓', keywords: ['food', 'breakfast', 'pork', 'pig', 'meat', 'brunch'] },
  'cooking': { name: 'cooking', char: '🍳', keywords: ['food', 'breakfast', 'kitchen', 'egg'] },
  'pancakes': { name: 'pancakes', char: '🥞', keywords: ['food', 'breakfast', 'flapjacks', 'hotcakes', 'brunch'] },
  'waffle': { name: 'waffle', char: '🧇', keywords: ['food', 'breakfast', 'brunch'] },
  'cut_of_meat': { name: 'cut_of_meat', char: '🥩', keywords: ['food', 'cow', 'meat', 'cut', 'chop', 'lambchop', 'porkchop'] },
  'poultry_leg': { name: 'poultry_leg', char: '🍗', keywords: ['food', 'meat', 'drumstick', 'bird', 'chicken', 'turkey'] },
  'meat_on_bone': { name: 'meat_on_bone', char: '🍖', keywords: ['good', 'food', 'drumstick'] },
  'bone_in_meat': { name: 'bone_in_meat', char: '🦴', keywords: ['food'] },
  'hotsprings': { name: 'hotsprings', char: '♨️', keywords: ['bath', 'warm', 'relax'] },
  
  // Nature
  'moon': { name: 'moon', char: '🌙', keywords: ['night', 'sleep', 'crescent'] },
  'tree': { name: 'tree', char: '🌳', keywords: ['nature', 'green', 'environment'] },
  'flower': { name: 'flower', char: '🌸', keywords: ['nature', 'pink', 'spring'] },
  'rainbow': { name: 'rainbow', char: '🌈', keywords: ['colorful', 'weather', 'pride'] }
};

export const EMOJI_LIST = Object.values(EMOJI_MAP);

export function searchEmojis(query: string): EmojiData[] {
  if (!query) return EMOJI_LIST.slice(0, 10); // Show first 10 by default
  
  const lowerQuery = query.toLowerCase();
  return EMOJI_LIST.filter(emoji => 
    emoji.name.includes(lowerQuery) || 
    emoji.keywords.some(keyword => keyword.includes(lowerQuery))
  ).slice(0, 10); // Limit to 10 results
}

export function getEmojiByName(name: string): EmojiData | undefined {
  return EMOJI_MAP[name];
}